CREATE DATABASE IF NOT EXISTS rajmudra_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE rajmudra_db;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS enquiries;
DROP TABLE IF EXISTS products;

CREATE TABLE products(id INT AUTO_INCREMENT PRIMARY KEY,category VARCHAR(50) NOT NULL,name VARCHAR(100) NOT NULL,description TEXT,price DECIMAL(10,2) NOT NULL,image VARCHAR(255),rating DECIMAL(2,1) DEFAULT 5.0,reviews_count INT DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE customers(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,phone VARCHAR(20),email VARCHAR(100),address TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE orders(id INT AUTO_INCREMENT PRIMARY KEY,customer_id INT,total_amount DECIMAL(10,2) NOT NULL,payment_method VARCHAR(50),status VARCHAR(50) DEFAULT 'Pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE order_items(id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,product_name VARCHAR(100) NOT NULL,price DECIMAL(10,2) NOT NULL,quantity INT NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE reviews(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,rating INT NOT NULL,review TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE enquiries(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,phone VARCHAR(20) NOT NULL,product VARCHAR(100),message TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('nath','Classic Nath','Beautiful nath jewellery inspired by Maharashtrian tradition.',349,'images/nath.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('nath','Pearl Nath','Beautiful nath jewellery inspired by Maharashtrian tradition.',399,'images/nath2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('nath','Floral Nath','Beautiful nath jewellery inspired by Maharashtrian tradition.',449,'images/nath3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('nath','Royal Nath','Beautiful nath jewellery inspired by Maharashtrian tradition.',499,'images/nath4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('nath','Traditional Nath','Beautiful nath jewellery inspired by Maharashtrian tradition.',549,'images/nath5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('nath','Minimal Nath','Beautiful nath jewellery inspired by Maharashtrian tradition.',599,'images/nath6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('earcuff','Classic Ear Cuff','Beautiful ear cuff jewellery inspired by Maharashtrian tradition.',299,'images/earcuff.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('earcuff','Pearl Ear Cuff','Beautiful ear cuff jewellery inspired by Maharashtrian tradition.',349,'images/earcuff2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('earcuff','Floral Ear Cuff','Beautiful ear cuff jewellery inspired by Maharashtrian tradition.',399,'images/earcuff3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('earcuff','Royal Ear Cuff','Beautiful ear cuff jewellery inspired by Maharashtrian tradition.',449,'images/earcuff4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('earcuff','Traditional Ear Cuff','Beautiful ear cuff jewellery inspired by Maharashtrian tradition.',499,'images/earcuff5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('earcuff','Minimal Ear Cuff','Beautiful ear cuff jewellery inspired by Maharashtrian tradition.',549,'images/earcuff6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('ring','Classic Ring','Beautiful ring jewellery inspired by Maharashtrian tradition.',249,'images/rings3.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('ring','Pearl Ring','Beautiful ring jewellery inspired by Maharashtrian tradition.',299,'images/ring2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('ring','Floral Ring','Beautiful ring jewellery inspired by Maharashtrian tradition.',349,'images/ring3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('ring','Royal Ring','Beautiful ring jewellery inspired by Maharashtrian tradition.',399,'images/ring4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('ring','Traditional Ring','Beautiful ring jewellery inspired by Maharashtrian tradition.',449,'images/ring5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('ring','Minimal Ring','Beautiful ring jewellery inspired by Maharashtrian tradition.',499,'images/ring6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('bugadi','Classic Bugadi','Beautiful bugadi jewellery inspired by Maharashtrian tradition.',399,'images/bugadi2.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('bugadi','Pearl Bugadi','Beautiful bugadi jewellery inspired by Maharashtrian tradition.',449,'images/bugadi2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('bugadi','Floral Bugadi','Beautiful bugadi jewellery inspired by Maharashtrian tradition.',499,'images/bugadi3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('bugadi','Royal Bugadi','Beautiful bugadi jewellery inspired by Maharashtrian tradition.',549,'images/bugadi4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('bugadi','Traditional Bugadi','Beautiful bugadi jewellery inspired by Maharashtrian tradition.',599,'images/bugadi5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('bugadi','Minimal Bugadi','Beautiful bugadi jewellery inspired by Maharashtrian tradition.',649,'images/bugadi6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('thushi','Classic Thushi','Beautiful thushi jewellery inspired by Maharashtrian tradition.',799,'images/thushi.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('thushi','Pearl Thushi','Beautiful thushi jewellery inspired by Maharashtrian tradition.',849,'images/thushi2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('thushi','Floral Thushi','Beautiful thushi jewellery inspired by Maharashtrian tradition.',899,'images/thushi3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('thushi','Royal Thushi','Beautiful thushi jewellery inspired by Maharashtrian tradition.',949,'images/thushi4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('thushi','Traditional Thushi','Beautiful thushi jewellery inspired by Maharashtrian tradition.',999,'images/thushi5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('thushi','Minimal Thushi','Beautiful thushi jewellery inspired by Maharashtrian tradition.',1049,'images/thushi6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('set','Classic Jewellery Set','Beautiful jewellery set jewellery inspired by Maharashtrian tradition.',899,'images/set.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('set','Pearl Jewellery Set','Beautiful jewellery set jewellery inspired by Maharashtrian tradition.',949,'images/set2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('set','Floral Jewellery Set','Beautiful jewellery set jewellery inspired by Maharashtrian tradition.',999,'images/set3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('set','Royal Jewellery Set','Beautiful jewellery set jewellery inspired by Maharashtrian tradition.',1049,'images/set4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('set','Traditional Jewellery Set','Beautiful jewellery set jewellery inspired by Maharashtrian tradition.',1099,'images/set5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('set','Minimal Jewellery Set','Beautiful jewellery set jewellery inspired by Maharashtrian tradition.',1149,'images/set6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('necklace','Classic Necklace','Beautiful necklace jewellery inspired by Maharashtrian tradition.',899,'images/necklace.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('necklace','Pearl Necklace','Beautiful necklace jewellery inspired by Maharashtrian tradition.',949,'images/necklace2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('necklace','Floral Necklace','Beautiful necklace jewellery inspired by Maharashtrian tradition.',999,'images/necklace3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('necklace','Royal Necklace','Beautiful necklace jewellery inspired by Maharashtrian tradition.',1049,'images/necklace4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('necklace','Traditional Necklace','Beautiful necklace jewellery inspired by Maharashtrian tradition.',1099,'images/necklace5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('necklace','Minimal Necklace','Beautiful necklace jewellery inspired by Maharashtrian tradition.',1149,'images/necklace6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('anklet','Classic Anklet','Beautiful anklet jewellery inspired by Maharashtrian tradition.',399,'images/anklet.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('anklet','Pearl Anklet','Beautiful anklet jewellery inspired by Maharashtrian tradition.',449,'images/anklet2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('anklet','Floral Anklet','Beautiful anklet jewellery inspired by Maharashtrian tradition.',499,'images/anklet3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('anklet','Royal Anklet','Beautiful anklet jewellery inspired by Maharashtrian tradition.',549,'images/anklet4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('anklet','Traditional Anklet','Beautiful anklet jewellery inspired by Maharashtrian tradition.',599,'images/anklet5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('anklet','Minimal Anklet','Beautiful anklet jewellery inspired by Maharashtrian tradition.',649,'images/anklet6.jpg',5.0,28);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('choker','Classic Choker','Beautiful choker jewellery inspired by Maharashtrian tradition.',799,'images/choker1.jpg',5.0,13);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('choker','Pearl Choker','Beautiful choker jewellery inspired by Maharashtrian tradition.',849,'images/choker2.jpg',5.0,16);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('choker','Floral Choker','Beautiful choker jewellery inspired by Maharashtrian tradition.',899,'images/choker3.jpg',5.0,19);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('choker','Royal Choker','Beautiful choker jewellery inspired by Maharashtrian tradition.',949,'images/choker4.jpg',5.0,22);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('choker','Traditional Choker','Beautiful choker jewellery inspired by Maharashtrian tradition.',999,'images/choker5.jpg',5.0,25);
INSERT INTO products(category,name,description,price,image,rating,reviews_count) VALUES('choker','Minimal Choker','Beautiful choker jewellery inspired by Maharashtrian tradition.',1049,'images/choker6.jpg',5.0,28);
